// Curated exercise library. Muscle/equipment data is factual; the cues are our
// own short wording. No third-party text or images are used.
import type {
  MuscleGroup,
  Equipment,
  ExerciseCategory,
} from "@prisma/client";

export type ExerciseSeed = {
  slug: string;
  name: string;
  category: ExerciseCategory;
  equipment: Equipment;
  primaryMuscles: MuscleGroup[];
  secondaryMuscles: MuscleGroup[];
  cues: string[];
};

export const EXERCISES: ExerciseSeed[] = [
  // ---- Push ----
  {
    slug: "barbell-bench-press",
    name: "Barbell Bench Press",
    category: "PUSH",
    equipment: "BARBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["SHOULDERS", "TRICEPS"],
    cues: [
      "Set shoulder blades back and down, feet flat.",
      "Lower the bar to mid-chest, then press up and slightly back.",
    ],
  },
  {
    slug: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    category: "PUSH",
    equipment: "DUMBBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["SHOULDERS", "TRICEPS"],
    cues: [
      "Keep wrists stacked over elbows.",
      "Press the dumbbells together at the top without clashing.",
    ],
  },
  {
    slug: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "PUSH",
    equipment: "DUMBBELL",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["SHOULDERS", "TRICEPS"],
    cues: [
      "Set the bench to roughly 30°.",
      "Drive through the upper chest, not the front delts.",
    ],
  },
  {
    slug: "push-up",
    name: "Push-Up",
    category: "PUSH",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["CHEST"],
    secondaryMuscles: ["SHOULDERS", "TRICEPS", "ABS"],
    cues: [
      "Brace the core so hips stay in line with shoulders.",
      "Keep elbows about 45° from the torso.",
    ],
  },
  {
    slug: "overhead-press",
    name: "Standing Overhead Press",
    category: "PUSH",
    equipment: "BARBELL",
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS", "TRAPS"],
    cues: [
      "Squeeze glutes and brace before pressing.",
      "Move the head 'through the window' as the bar passes the face.",
    ],
  },
  {
    slug: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    category: "PUSH",
    equipment: "DUMBBELL",
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: ["TRICEPS"],
    cues: ["Stop just short of locking out.", "Avoid arching the lower back."],
  },
  {
    slug: "lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "PUSH",
    equipment: "DUMBBELL",
    primaryMuscles: ["SHOULDERS"],
    secondaryMuscles: [],
    cues: ["Lead with the elbows, not the hands.", "Raise to shoulder height only."],
  },
  {
    slug: "triceps-pushdown",
    name: "Cable Triceps Pushdown",
    category: "PUSH",
    equipment: "CABLE",
    primaryMuscles: ["TRICEPS"],
    secondaryMuscles: [],
    cues: ["Keep elbows pinned to your sides.", "Fully straighten without leaning."],
  },
  {
    slug: "dips",
    name: "Parallel Bar Dips",
    category: "PUSH",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["CHEST", "TRICEPS"],
    secondaryMuscles: ["SHOULDERS"],
    cues: [
      "Lean forward for chest, stay upright for triceps.",
      "Lower until upper arms are about parallel.",
    ],
  },

  // ---- Pull ----
  {
    slug: "deadlift",
    name: "Conventional Deadlift",
    category: "FULL_BODY",
    equipment: "BARBELL",
    primaryMuscles: ["GLUTES", "HAMSTRINGS", "LOWER_BACK"],
    secondaryMuscles: ["TRAPS", "LATS", "FOREARMS", "QUADS"],
    cues: [
      "Bar over mid-foot, take the slack out before pulling.",
      "Push the floor away and keep the bar close to the legs.",
    ],
  },
  {
    slug: "pull-up",
    name: "Pull-Up",
    category: "PULL",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["BICEPS", "UPPER_BACK", "FOREARMS"],
    cues: ["Start from a full hang.", "Drive the elbows down toward the hips."],
  },
  {
    slug: "lat-pulldown",
    name: "Lat Pulldown",
    category: "PULL",
    equipment: "CABLE",
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["BICEPS", "UPPER_BACK"],
    cues: ["Pull the bar to the upper chest.", "Avoid swinging the torso."],
  },
  {
    slug: "bent-over-barbell-row",
    name: "Bent-Over Barbell Row",
    category: "PULL",
    equipment: "BARBELL",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["LATS", "BICEPS", "LOWER_BACK"],
    cues: ["Hinge to about 45°, flat back.", "Row to the lower ribs."],
  },
  {
    slug: "seated-cable-row",
    name: "Seated Cable Row",
    category: "PULL",
    equipment: "CABLE",
    primaryMuscles: ["UPPER_BACK"],
    secondaryMuscles: ["LATS", "BICEPS"],
    cues: ["Keep the chest tall.", "Squeeze the shoulder blades at the end."],
  },
  {
    slug: "dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    category: "PULL",
    equipment: "DUMBBELL",
    primaryMuscles: ["LATS"],
    secondaryMuscles: ["UPPER_BACK", "BICEPS"],
    cues: ["Support the free hand on the bench.", "Drive the elbow toward the hip."],
  },
  {
    slug: "face-pull",
    name: "Cable Face Pull",
    category: "PULL",
    equipment: "CABLE",
    primaryMuscles: ["SHOULDERS", "TRAPS"],
    secondaryMuscles: ["UPPER_BACK"],
    cues: ["Pull toward the forehead.", "Externally rotate so thumbs point back."],
  },
  {
    slug: "barbell-biceps-curl",
    name: "Barbell Biceps Curl",
    category: "PULL",
    equipment: "BARBELL",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    cues: ["Keep elbows still at your sides.", "Avoid using the hips to swing."],
  },
  {
    slug: "dumbbell-hammer-curl",
    name: "Dumbbell Hammer Curl",
    category: "PULL",
    equipment: "DUMBBELL",
    primaryMuscles: ["BICEPS"],
    secondaryMuscles: ["FOREARMS"],
    cues: ["Hold a neutral grip throughout.", "Control the lowering phase."],
  },
  {
    slug: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    category: "PULL",
    equipment: "DUMBBELL",
    primaryMuscles: ["TRAPS"],
    secondaryMuscles: ["FOREARMS"],
    cues: ["Lift straight up, no rolling.", "Pause briefly at the top."],
  },

  // ---- Legs ----
  {
    slug: "back-squat",
    name: "Barbell Back Squat",
    category: "LEGS",
    equipment: "BARBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS", "LOWER_BACK"],
    cues: ["Brace and break at hips and knees together.", "Drive the knees out."],
  },
  {
    slug: "front-squat",
    name: "Barbell Front Squat",
    category: "LEGS",
    equipment: "BARBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "ABS"],
    cues: ["Keep the elbows high.", "Stay upright through the torso."],
  },
  {
    slug: "goblet-squat",
    name: "Goblet Squat",
    category: "LEGS",
    equipment: "DUMBBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES"],
    cues: ["Hold the weight at chest height.", "Sit down between the knees."],
  },
  {
    slug: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "LEGS",
    equipment: "BARBELL",
    primaryMuscles: ["HAMSTRINGS"],
    secondaryMuscles: ["GLUTES", "LOWER_BACK"],
    cues: ["Push the hips back with soft knees.", "Stop when you feel the stretch."],
  },
  {
    slug: "leg-press",
    name: "Leg Press",
    category: "LEGS",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    cues: ["Keep the lower back on the pad.", "Don't lock the knees hard at the top."],
  },
  {
    slug: "walking-lunge",
    name: "Walking Lunge",
    category: "LEGS",
    equipment: "DUMBBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    cues: ["Take a long step, drop the back knee.", "Keep the front shin vertical-ish."],
  },
  {
    slug: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "LEGS",
    equipment: "DUMBBELL",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    cues: ["Rear foot on the bench.", "Sink straight down over the front heel."],
  },
  {
    slug: "leg-curl",
    name: "Lying Leg Curl",
    category: "LEGS",
    equipment: "MACHINE",
    primaryMuscles: ["HAMSTRINGS"],
    secondaryMuscles: ["CALVES"],
    cues: ["Keep hips pressed down.", "Squeeze at full flexion."],
  },
  {
    slug: "leg-extension",
    name: "Leg Extension",
    category: "LEGS",
    equipment: "MACHINE",
    primaryMuscles: ["QUADS"],
    secondaryMuscles: [],
    cues: ["Pause at the top.", "Lower under control."],
  },
  {
    slug: "hip-thrust",
    name: "Barbell Hip Thrust",
    category: "LEGS",
    equipment: "BARBELL",
    primaryMuscles: ["GLUTES"],
    secondaryMuscles: ["HAMSTRINGS"],
    cues: ["Tuck the chin and ribs.", "Drive the hips to full lockout, squeeze glutes."],
  },
  {
    slug: "standing-calf-raise",
    name: "Standing Calf Raise",
    category: "LEGS",
    equipment: "MACHINE",
    primaryMuscles: ["CALVES"],
    secondaryMuscles: [],
    cues: ["Use a full range over the toes.", "Pause at the top stretch and squeeze."],
  },

  // ---- Core ----
  {
    slug: "plank",
    name: "Plank",
    category: "CORE",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: ["OBLIQUES"],
    cues: ["Squeeze glutes and brace the abs.", "Keep a straight line head to heels."],
  },
  {
    slug: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    category: "CORE",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: ["OBLIQUES", "FOREARMS"],
    cues: ["Avoid swinging.", "Curl the pelvis up, not just the legs."],
  },
  {
    slug: "cable-crunch",
    name: "Cable Crunch",
    category: "CORE",
    equipment: "CABLE",
    primaryMuscles: ["ABS"],
    secondaryMuscles: [],
    cues: ["Round the spine down toward the knees.", "Keep the hips fixed."],
  },
  {
    slug: "russian-twist",
    name: "Russian Twist",
    category: "CORE",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["OBLIQUES"],
    secondaryMuscles: ["ABS"],
    cues: ["Rotate from the ribcage.", "Keep the chest tall."],
  },
  {
    slug: "back-extension",
    name: "Back Extension",
    category: "CORE",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["LOWER_BACK"],
    secondaryMuscles: ["GLUTES", "HAMSTRINGS"],
    cues: ["Extend to a straight line, no hyperextension.", "Squeeze the glutes at the top."],
  },

  // ---- Conditioning / full body ----
  {
    slug: "burpee",
    name: "Burpee",
    category: "CARDIO",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["FULL_BODY"],
    secondaryMuscles: ["CHEST", "QUADS", "SHOULDERS"],
    cues: ["Keep a steady rhythm.", "Land softly from the jump."],
  },
  {
    slug: "kettlebell-swing",
    name: "Kettlebell Swing",
    category: "FULL_BODY",
    equipment: "KETTLEBELL",
    primaryMuscles: ["GLUTES", "HAMSTRINGS"],
    secondaryMuscles: ["LOWER_BACK", "SHOULDERS"],
    cues: ["Power comes from a hip snap, not the arms.", "Float the bell to chest height."],
  },
  {
    slug: "mountain-climber",
    name: "Mountain Climber",
    category: "CARDIO",
    equipment: "BODYWEIGHT",
    primaryMuscles: ["ABS"],
    secondaryMuscles: ["SHOULDERS", "QUADS"],
    cues: ["Keep the hips low and level.", "Drive the knees quickly."],
  },
];
